name: CI
run-name: CI tests
on:
  workflow_dispatch:
  push:
    branches:
      - 0.14.x
      - 0.15.x
      - master
    paths:
      - '**.zig'
      - '**.zon'
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at 00:00 UTC
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test on linux
    timeout-minutes: 5
    strategy:
      matrix:
        zig_version: ["master"]
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Setup zig environment"
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig_version }}
      - name: "Run linter"
        run: zig build lint
